export const
  ARTICLES_REQUESTED = "ARTICLES_REQUESTED",
  ARTICLE_REQUESTED = "ARTICLE_REQUESTED",
  API_ERRORED = "API_ERRORED",
  ARTICLES_LOADED = "ARTICLES_LOADED",
  ARTICLE_LOADED = "ARTICLE_LOADED";
